### ISSUE TITLE
Considering pure React Native / Expo template

### ISSUE THREAD

**Issue by Aichnerc** [chen-rn/CUA#16]
Hey man,
have you considered creating a pure expo project (without web, nextjs), with an explanation of how to build, publish and update the expo app using `eas`?

Cheers!

**Comment by chen-rn** [comment]
Though I'm not too sure what you mean by a "pure" expo project, but I can definitely do something where we walk through how to go from start to having the app on your phone w/ EAS!

**Comment by redbar0n** [comment]
@Aichnerc I’ve collected a list of all the React Nativestarter monorepos I’ve come across here (scroll down to my recommendation section):

https://dev.to/this-is-learning/the-different-strategies-to-building-a-cross-platform-app-3p56

Specifically, you might want to check out:

[Luna](https://github.com/criszz77/luna) which is a monorepo starter that has Tamagui + Solito + Next.js, and like the others is made with TypeScript and React Native Web. But it is for those that want a bare React Native setup, since it comes without Expo.

**Comment by chen-rn** [comment]
@redbar0n Ahhh very very cool :)

PS: [ebg1223](https://github.com/ebg1223) the marker of t3-tamagui has joined CUA :)
He added a fantastic new branch with expo-router, and I think we'll likely make the main branch in the near future!

**Comment by redbar0n** [comment]
glad you like it :) yeah I saw that! will likely remove t3-tamagui  from the list then. Awesome with Expo Router!
