### ISSUE TITLE
Type Error with my/ui

### ISSUE THREAD

**Issue by gascenciom1998** [chen-rn/CUA#20]
Getting a type error on imports from my/ui, specifically in tamagui.config.ts

Any idea how to make that go? 

<img width="795" alt="Screenshot 2023-01-24 at 6 48 52 PM" src="https://user-images.githubusercontent.com/30400139/214454928-10892dc6-eb4e-47bb-ad10-c769c6429dd2.png">

**Comment by chen-rn** [comment]
I will look into this! It happens to me as well! Must be caused by some renaming.

**Comment by chen-rn** [comment]
Okay, it seems that this problem happened because we opened the file before the UI libraries were built.

However, even after the UI library gets built, like VSCode typescript linter does not update. Which is a VSCode cache problem.

(If you delete any character from the @my/ui, and add it back in, it seems that the error goes away as well. But all import errors stay)

So, what I've [done now](https://github.com/chen-rn/CUA/commit/144ace975e1c6b4d14249b1321e93a4faaa04e69), is to automatically build the UI library after install. This way, VSCode should always have types from @my/ui!

If you don't want to reclone, you can also fix this by doing CMD+SHIFT+P, enter "typescript version", and reselect the VSCode version. For example, going from "Workspace typescript" to ""VSCode typescript" and back. It should re-instantiate your typescript linter!

<img width="1034" alt="Screenshot 2023-01-27 at 9 58 32 AM" src="https://user-images.githubusercontent.com/36214945/215160175-9c521b6b-c467-40e2-bf38-2d8efb1a62f7.png">

**Comment by patrykczubek** [comment]
Once I did that, for some reason my entire file broke.

`import { Button, Paragraph, Separator, XStack, YStack, Card, H3, } from "@my/ui";`

![image](https://user-images.githubusercontent.com/67239078/215291244-27a872e7-5b77-4ddb-b664-0cacd500414c.png)


![image](https://user-images.githubusercontent.com/67239078/215291247-b5bd6304-4c4b-49d5-a835-a23366ec3a85.png)
