### ISSUE TITLE
.env not working in root

### ISSUE THREAD

**Issue by gascenciom1998** [chen-rn/CUA#9]
I started from an existing nextjs web app, migrated everything to CUA (basically just putting my nextJS app insice apps/web). For some reason the environment variables are undefined, but it does work if I move .env inside apps/web. Still that feels wrong and I want to share the env variables across both apps but I think I may be missing some configurations somewhere.

**Comment by jllewis11** [comment]
For the .env in the DB folder, I had to manually link it by stating in the main package.json

`"prisma": {
  "schema": "./packages/db/prisma/schema.prisma
},`

[Prisma env docs](https://www.prisma.io/docs/guides/development-environment/environment-variables)
From here, the third option.

I'm not too sure if @chen-rn would like to add this to the main package.json, so the db's env can be utilized.

**Comment by chen-rn** [comment]
Hey!

So the env thing should've been fixed in one of the [early commits](https://github.com/chen-rn/CUA/commit/c8f34787dd2e15d142bbc730197cf1fe86f703ff), did you happen to have cloned before that? @jllewis11 


@gascenciom1998 does your db package.json have [this line?](https://github.com/chen-rn/CUA/blob/main/packages/db/package.json#:~:text=%22with%2Denv%22%3A%20%22dotenv%20%2De%20../../.env%20%2D%2D%22%2C)

**Comment by chen-rn** [comment]
Also, I think the package.jsons overall can have some improvements as well. Use more turbo build stuff, less yarn stuff, etc!

**Comment by chen-rn** [comment]
It seems that without this line, you're able to use Prisma in dev but not in prod. I've added it to the root package json! Thanks for the tip Jerry @jllewis11
